version: 2

jobs:
  foo:
    docker:
      - image: centos:7
    steps:
      - run: echo foo
  bar:
    docker:
      - image: centos:7
    steps:
      - run: echo hi

workflows:
  version: 2
  run_foo:
    jobs:
      - foo:
          filters:
            branches:
              only:
                - /trying-.*/
                - /staging-.*/
      - bar:
          requires:
            - foo
