version: 2

jobs:
  foo:
    docker:
      - image: centos:7
    steps:
      - run: sleep 540 # sleep for 9 minutes
  bar:
    docker:
      - image: centos:7
    steps:
      - run: echo hi

workflows:
  version: 2
  run_foo:
    jobs:
      - foo
      - bar:
          requires:
            - foo
