version: 2

jobs:
  foo:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo foo
  bar:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          command: sleep 3600
          no_output_timeout: 30m
      - run: cat non-existent
  baz:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo baz

workflows:
  version: 2
  run_foo:
    jobs:
      - foo:
          filters:
            branches:
              only:
                - /trying-.*/
                - /staging-.*/
      - bar:
          requires:
            - foo
      - baz:
          requires:
            - bar
